name: Publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install mkdocs mkdocs-video mkdocs-mermaid2-plugin mkdocs-cluster mkdocs-bootstrap4 mkdocs-bootswatch
          mkdir dist
      - name: Build the site
        run: |
          mkdocs build -f mkdocs.yml -d dist -c --no-directory-urls
      - name: Publish to Cloudflare
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'ismsowner'
          directory: './dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
