name: Publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install mkdocs mkdocs-video mkdocs-mermaid2-plugin mkdocs-cluster mkdocs-bootstrap4 mkdocs-bootswatch
          mkdir dist
      - name: Build the site
        run: |
          mkdocs build -f mkdocs.yml -d dist -c --no-directory-urls
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-2
          AWS_S3_BUCKET: www.ismsowner.com
        run: |
          aws s3 sync dist s3://$AWS_S3_BUCKET
      - name: Publish to Cloudflare
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'ismsowner'
          directory: './dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
